//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.12 at 04:49:51 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://swmud.pl/ns/swaedit/stringtypes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.swmud.ns.swaedit.stringtypes;
