//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.23 at 09:57:04 AM CET 
//


package pl.swmud.ns.swaedit.lastupdate;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.swmud.ns.swaedit.lastupdate package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Lastupdate_QNAME = new QName("http://swmud.pl/ns/swaedit/lastupdate", "lastupdate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.swmud.ns.swaedit.lastupdate
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Lastupdate }
     * 
     */
    public Lastupdate createLastupdate() {
        return new Lastupdate();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Lastupdate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://swmud.pl/ns/swaedit/lastupdate", name = "lastupdate")
    public JAXBElement<Lastupdate> createLastupdate(Lastupdate value) {
        return new JAXBElement<Lastupdate>(_Lastupdate_QNAME, Lastupdate.class, null, value);
    }

}
