//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.25 at 07:22:39 PM CET 
//


package pl.swmud.ns.swmud._1_0.area;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for area complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="area">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="head" type="{http://swmud.pl/ns/swmud/1.0/area}head"/>
 *         &lt;element name="mobiles" type="{http://swmud.pl/ns/swmud/1.0/area}mobiles"/>
 *         &lt;element name="objects" type="{http://swmud.pl/ns/swmud/1.0/area}objects"/>
 *         &lt;element name="rooms" type="{http://swmud.pl/ns/swmud/1.0/area}rooms"/>
 *         &lt;element name="resets" type="{http://swmud.pl/ns/swmud/1.0/area}resets"/>
 *         &lt;element name="shops" type="{http://swmud.pl/ns/swmud/1.0/area}shops"/>
 *         &lt;element name="repairs" type="{http://swmud.pl/ns/swmud/1.0/area}repairs"/>
 *         &lt;element name="specials" type="{http://swmud.pl/ns/swmud/1.0/area}specials"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "area", propOrder = {
    "head",
    "mobiles",
    "objects",
    "rooms",
    "resets",
    "shops",
    "repairs",
    "specials"
})
@XmlRootElement
public class Area {

    @XmlElement(required = true)
    protected Head head;
    @XmlElement(required = true)
    protected Mobiles mobiles;
    @XmlElement(required = true)
    protected Objects objects;
    @XmlElement(required = true)
    protected Rooms rooms;
    @XmlElement(required = true)
    protected Resets resets;
    @XmlElement(required = true)
    protected Shops shops;
    @XmlElement(required = true)
    protected Repairs repairs;
    @XmlElement(required = true)
    protected Specials specials;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link Head }
     *     
     */
    public Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link Head }
     *     
     */
    public void setHead(Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the mobiles property.
     * 
     * @return
     *     possible object is
     *     {@link Mobiles }
     *     
     */
    public Mobiles getMobiles() {
        return mobiles;
    }

    /**
     * Sets the value of the mobiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mobiles }
     *     
     */
    public void setMobiles(Mobiles value) {
        this.mobiles = value;
    }

    /**
     * Gets the value of the objects property.
     * 
     * @return
     *     possible object is
     *     {@link Objects }
     *     
     */
    public Objects getObjects() {
        return objects;
    }

    /**
     * Sets the value of the objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Objects }
     *     
     */
    public void setObjects(Objects value) {
        this.objects = value;
    }

    /**
     * Gets the value of the rooms property.
     * 
     * @return
     *     possible object is
     *     {@link Rooms }
     *     
     */
    public Rooms getRooms() {
        return rooms;
    }

    /**
     * Sets the value of the rooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rooms }
     *     
     */
    public void setRooms(Rooms value) {
        this.rooms = value;
    }

    /**
     * Gets the value of the resets property.
     * 
     * @return
     *     possible object is
     *     {@link Resets }
     *     
     */
    public Resets getResets() {
        return resets;
    }

    /**
     * Sets the value of the resets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resets }
     *     
     */
    public void setResets(Resets value) {
        this.resets = value;
    }

    /**
     * Gets the value of the shops property.
     * 
     * @return
     *     possible object is
     *     {@link Shops }
     *     
     */
    public Shops getShops() {
        return shops;
    }

    /**
     * Sets the value of the shops property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shops }
     *     
     */
    public void setShops(Shops value) {
        this.shops = value;
    }

    /**
     * Gets the value of the repairs property.
     * 
     * @return
     *     possible object is
     *     {@link Repairs }
     *     
     */
    public Repairs getRepairs() {
        return repairs;
    }

    /**
     * Sets the value of the repairs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Repairs }
     *     
     */
    public void setRepairs(Repairs value) {
        this.repairs = value;
    }

    /**
     * Gets the value of the specials property.
     * 
     * @return
     *     possible object is
     *     {@link Specials }
     *     
     */
    public Specials getSpecials() {
        return specials;
    }

    /**
     * Sets the value of the specials property.
     * 
     * @param value
     *     allowed object is
     *     {@link Specials }
     *     
     */
    public void setSpecials(Specials value) {
        this.specials = value;
    }

}
