//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.25 at 07:22:39 PM CET 
//


package pl.swmud.ns.swmud._1_0.area;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for head complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="head">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *         &lt;element name="authors" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *         &lt;element name="builders" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *         &lt;element name="security" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="vnums">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="lvnum" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                   &lt;element name="uvnum" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="flags" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="economy">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="low" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                   &lt;element name="high" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="reset">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="frequency" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ranges">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="low" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="high" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "head", propOrder = {
    "name",
    "authors",
    "builders",
    "security",
    "vnums",
    "flags",
    "economy",
    "reset",
    "ranges"
})
public class Head {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String authors;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String builders;
    protected short security;
    @XmlElement(required = true)
    protected Head.Vnums vnums;
    protected long flags;
    @XmlElement(required = true)
    protected Head.Economy economy;
    @XmlElement(required = true)
    protected Head.Reset reset;
    @XmlElement(required = true)
    protected Head.Ranges ranges;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the authors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthors() {
        return authors;
    }

    /**
     * Sets the value of the authors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthors(String value) {
        this.authors = value;
    }

    /**
     * Gets the value of the builders property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuilders() {
        return builders;
    }

    /**
     * Sets the value of the builders property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuilders(String value) {
        this.builders = value;
    }

    /**
     * Gets the value of the security property.
     * 
     */
    public short getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     */
    public void setSecurity(short value) {
        this.security = value;
    }

    /**
     * Gets the value of the vnums property.
     * 
     * @return
     *     possible object is
     *     {@link Head.Vnums }
     *     
     */
    public Head.Vnums getVnums() {
        return vnums;
    }

    /**
     * Sets the value of the vnums property.
     * 
     * @param value
     *     allowed object is
     *     {@link Head.Vnums }
     *     
     */
    public void setVnums(Head.Vnums value) {
        this.vnums = value;
    }

    /**
     * Gets the value of the flags property.
     * 
     */
    public long getFlags() {
        return flags;
    }

    /**
     * Sets the value of the flags property.
     * 
     */
    public void setFlags(long value) {
        this.flags = value;
    }

    /**
     * Gets the value of the economy property.
     * 
     * @return
     *     possible object is
     *     {@link Head.Economy }
     *     
     */
    public Head.Economy getEconomy() {
        return economy;
    }

    /**
     * Sets the value of the economy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Head.Economy }
     *     
     */
    public void setEconomy(Head.Economy value) {
        this.economy = value;
    }

    /**
     * Gets the value of the reset property.
     * 
     * @return
     *     possible object is
     *     {@link Head.Reset }
     *     
     */
    public Head.Reset getReset() {
        return reset;
    }

    /**
     * Sets the value of the reset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Head.Reset }
     *     
     */
    public void setReset(Head.Reset value) {
        this.reset = value;
    }

    /**
     * Gets the value of the ranges property.
     * 
     * @return
     *     possible object is
     *     {@link Head.Ranges }
     *     
     */
    public Head.Ranges getRanges() {
        return ranges;
    }

    /**
     * Sets the value of the ranges property.
     * 
     * @param value
     *     allowed object is
     *     {@link Head.Ranges }
     *     
     */
    public void setRanges(Head.Ranges value) {
        this.ranges = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="low" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *         &lt;element name="high" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "low",
        "high"
    })
    public static class Economy {

        protected long low;
        protected long high;

        /**
         * Gets the value of the low property.
         * 
         */
        public long getLow() {
            return low;
        }

        /**
         * Sets the value of the low property.
         * 
         */
        public void setLow(long value) {
            this.low = value;
        }

        /**
         * Gets the value of the high property.
         * 
         */
        public long getHigh() {
            return high;
        }

        /**
         * Sets the value of the high property.
         * 
         */
        public void setHigh(long value) {
            this.high = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="low" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="high" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "low",
        "high"
    })
    public static class Ranges {

        protected short low;
        protected short high;

        /**
         * Gets the value of the low property.
         * 
         */
        public short getLow() {
            return low;
        }

        /**
         * Sets the value of the low property.
         * 
         */
        public void setLow(short value) {
            this.low = value;
        }

        /**
         * Gets the value of the high property.
         * 
         */
        public short getHigh() {
            return high;
        }

        /**
         * Sets the value of the high property.
         * 
         */
        public void setHigh(short value) {
            this.high = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="frequency" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "frequency",
        "message"
    })
    public static class Reset {

        protected int frequency;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String message;

        /**
         * Gets the value of the frequency property.
         * 
         */
        public int getFrequency() {
            return frequency;
        }

        /**
         * Sets the value of the frequency property.
         * 
         */
        public void setFrequency(int value) {
            this.frequency = value;
        }

        /**
         * Gets the value of the message property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessage() {
            return message;
        }

        /**
         * Sets the value of the message property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessage(String value) {
            this.message = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="lvnum" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *         &lt;element name="uvnum" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lvnum",
        "uvnum"
    })
    public static class Vnums {

        @XmlElement(required = true)
        protected BigInteger lvnum;
        @XmlElement(required = true)
        protected BigInteger uvnum;

        /**
         * Gets the value of the lvnum property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getLvnum() {
            return lvnum;
        }

        /**
         * Sets the value of the lvnum property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setLvnum(BigInteger value) {
            this.lvnum = value;
        }

        /**
         * Gets the value of the uvnum property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getUvnum() {
            return uvnum;
        }

        /**
         * Sets the value of the uvnum property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setUvnum(BigInteger value) {
            this.uvnum = value;
        }

    }

}
