//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.25 at 07:22:39 PM CET 
//


package pl.swmud.ns.swmud._1_0.area;

import java.math.BigInteger;
import java.util.LinkedList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for mobiles complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mobiles">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mobile" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="vnum" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *                   &lt;element name="short" type="{http://swmud.pl/ns/swmud/1.0/area}short"/>
 *                   &lt;element name="long" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="race" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *                   &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="act" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="affected" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="sex" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="credits" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                   &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="sectiona" type="{http://swmud.pl/ns/swmud/1.0/area}sectiona"/>
 *                   &lt;element name="sections" type="{http://swmud.pl/ns/swmud/1.0/area}sections"/>
 *                   &lt;element name="sectionr" type="{http://swmud.pl/ns/swmud/1.0/area}sectionr"/>
 *                   &lt;element name="sectionx" type="{http://swmud.pl/ns/swmud/1.0/area}sectionx"/>
 *                   &lt;element name="sectiont" type="{http://swmud.pl/ns/swmud/1.0/area}sectiont"/>
 *                   &lt;element name="sectionv" type="{http://swmud.pl/ns/swmud/1.0/area}sectionv"/>
 *                   &lt;element name="dialog" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="programs" type="{http://swmud.pl/ns/swmud/1.0/area}programs"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mobiles", propOrder = {
    "mobile"
})
public class Mobiles {

    protected List<Mobiles.Mobile> mobile = new LinkedList<Mobiles.Mobile>();

    /**
     * Gets the value of the mobile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mobile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMobile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mobiles.Mobile }
     * 
     * 
     */
    public List<Mobiles.Mobile> getMobile() {
        if (mobile == null) {
            mobile = new LinkedList<Mobiles.Mobile>();
        }
        return this.mobile;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="vnum" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
     *         &lt;element name="short" type="{http://swmud.pl/ns/swmud/1.0/area}short"/>
     *         &lt;element name="long" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="race" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
     *         &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="act" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="affected" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="sex" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="credits" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *         &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="sectiona" type="{http://swmud.pl/ns/swmud/1.0/area}sectiona"/>
     *         &lt;element name="sections" type="{http://swmud.pl/ns/swmud/1.0/area}sections"/>
     *         &lt;element name="sectionr" type="{http://swmud.pl/ns/swmud/1.0/area}sectionr"/>
     *         &lt;element name="sectionx" type="{http://swmud.pl/ns/swmud/1.0/area}sectionx"/>
     *         &lt;element name="sectiont" type="{http://swmud.pl/ns/swmud/1.0/area}sectiont"/>
     *         &lt;element name="sectionv" type="{http://swmud.pl/ns/swmud/1.0/area}sectionv"/>
     *         &lt;element name="dialog" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="programs" type="{http://swmud.pl/ns/swmud/1.0/area}programs"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vnum",
        "name",
        "_short",
        "_long",
        "description",
        "race",
        "level",
        "act",
        "affected",
        "alignment",
        "sex",
        "credits",
        "position",
        "sectiona",
        "sections",
        "sectionr",
        "sectionx",
        "sectiont",
        "sectionv",
        "dialog",
        "programs"
    })
    public static class Mobile {

        @XmlElement(required = true)
        protected BigInteger vnum;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String name;
        @XmlElement(name = "short", required = true)
        protected Short _short;
        @XmlElement(name = "long", required = true)
        protected String _long;
        @XmlElement(required = true)
        protected String description;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String race;
        protected int level;
        protected long act;
        protected long affected;
        protected short alignment;
        protected short sex;
        protected long credits;
        protected short position;
        @XmlElement(required = true)
        protected Sectiona sectiona;
        @XmlElement(required = true)
        protected Sections sections;
        @XmlElement(required = true)
        protected Sectionr sectionr;
        @XmlElement(required = true)
        protected Sectionx sectionx;
        @XmlElement(required = true)
        protected Sectiont sectiont;
        @XmlElement(required = true)
        protected Sectionv sectionv;
        @XmlElement(required = true)
        protected String dialog;
        @XmlElement(required = true)
        protected Programs programs;

        /**
         * Gets the value of the vnum property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getVnum() {
            return vnum;
        }

        /**
         * Sets the value of the vnum property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setVnum(BigInteger value) {
            this.vnum = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the short property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getShort() {
            return _short;
        }

        /**
         * Sets the value of the short property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setShort(Short value) {
            this._short = value;
        }

        /**
         * Gets the value of the long property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLong() {
            return _long;
        }

        /**
         * Sets the value of the long property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLong(String value) {
            this._long = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the race property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRace() {
            return race;
        }

        /**
         * Sets the value of the race property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRace(String value) {
            this.race = value;
        }

        /**
         * Gets the value of the level property.
         * 
         */
        public int getLevel() {
            return level;
        }

        /**
         * Sets the value of the level property.
         * 
         */
        public void setLevel(int value) {
            this.level = value;
        }

        /**
         * Gets the value of the act property.
         * 
         */
        public long getAct() {
            return act;
        }

        /**
         * Sets the value of the act property.
         * 
         */
        public void setAct(long value) {
            this.act = value;
        }

        /**
         * Gets the value of the affected property.
         * 
         */
        public long getAffected() {
            return affected;
        }

        /**
         * Sets the value of the affected property.
         * 
         */
        public void setAffected(long value) {
            this.affected = value;
        }

        /**
         * Gets the value of the alignment property.
         * 
         */
        public short getAlignment() {
            return alignment;
        }

        /**
         * Sets the value of the alignment property.
         * 
         */
        public void setAlignment(short value) {
            this.alignment = value;
        }

        /**
         * Gets the value of the sex property.
         * 
         */
        public short getSex() {
            return sex;
        }

        /**
         * Sets the value of the sex property.
         * 
         */
        public void setSex(short value) {
            this.sex = value;
        }

        /**
         * Gets the value of the credits property.
         * 
         */
        public long getCredits() {
            return credits;
        }

        /**
         * Sets the value of the credits property.
         * 
         */
        public void setCredits(long value) {
            this.credits = value;
        }

        /**
         * Gets the value of the position property.
         * 
         */
        public short getPosition() {
            return position;
        }

        /**
         * Sets the value of the position property.
         * 
         */
        public void setPosition(short value) {
            this.position = value;
        }

        /**
         * Gets the value of the sectiona property.
         * 
         * @return
         *     possible object is
         *     {@link Sectiona }
         *     
         */
        public Sectiona getSectiona() {
            return sectiona;
        }

        /**
         * Sets the value of the sectiona property.
         * 
         * @param value
         *     allowed object is
         *     {@link Sectiona }
         *     
         */
        public void setSectiona(Sectiona value) {
            this.sectiona = value;
        }

        /**
         * Gets the value of the sections property.
         * 
         * @return
         *     possible object is
         *     {@link Sections }
         *     
         */
        public Sections getSections() {
            return sections;
        }

        /**
         * Sets the value of the sections property.
         * 
         * @param value
         *     allowed object is
         *     {@link Sections }
         *     
         */
        public void setSections(Sections value) {
            this.sections = value;
        }

        /**
         * Gets the value of the sectionr property.
         * 
         * @return
         *     possible object is
         *     {@link Sectionr }
         *     
         */
        public Sectionr getSectionr() {
            return sectionr;
        }

        /**
         * Sets the value of the sectionr property.
         * 
         * @param value
         *     allowed object is
         *     {@link Sectionr }
         *     
         */
        public void setSectionr(Sectionr value) {
            this.sectionr = value;
        }

        /**
         * Gets the value of the sectionx property.
         * 
         * @return
         *     possible object is
         *     {@link Sectionx }
         *     
         */
        public Sectionx getSectionx() {
            return sectionx;
        }

        /**
         * Sets the value of the sectionx property.
         * 
         * @param value
         *     allowed object is
         *     {@link Sectionx }
         *     
         */
        public void setSectionx(Sectionx value) {
            this.sectionx = value;
        }

        /**
         * Gets the value of the sectiont property.
         * 
         * @return
         *     possible object is
         *     {@link Sectiont }
         *     
         */
        public Sectiont getSectiont() {
            return sectiont;
        }

        /**
         * Sets the value of the sectiont property.
         * 
         * @param value
         *     allowed object is
         *     {@link Sectiont }
         *     
         */
        public void setSectiont(Sectiont value) {
            this.sectiont = value;
        }

        /**
         * Gets the value of the sectionv property.
         * 
         * @return
         *     possible object is
         *     {@link Sectionv }
         *     
         */
        public Sectionv getSectionv() {
            return sectionv;
        }

        /**
         * Sets the value of the sectionv property.
         * 
         * @param value
         *     allowed object is
         *     {@link Sectionv }
         *     
         */
        public void setSectionv(Sectionv value) {
            this.sectionv = value;
        }

        /**
         * Gets the value of the dialog property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDialog() {
            return dialog;
        }

        /**
         * Sets the value of the dialog property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDialog(String value) {
            this.dialog = value;
        }

        /**
         * Gets the value of the programs property.
         * 
         * @return
         *     possible object is
         *     {@link Programs }
         *     
         */
        public Programs getPrograms() {
            return programs;
        }

        /**
         * Sets the value of the programs property.
         * 
         * @param value
         *     allowed object is
         *     {@link Programs }
         *     
         */
        public void setPrograms(Programs value) {
            this.programs = value;
        }

    }

}
