//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.25 at 07:22:39 PM CET 
//


package pl.swmud.ns.swmud._1_0.area;

import java.math.BigInteger;
import java.util.LinkedList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for objects complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="objects">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="object" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="vnum" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *                   &lt;element name="short" type="{http://swmud.pl/ns/swmud/1.0/area}short"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="actiondesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="extraflags" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="wearflags" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="layers" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="values">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="value0" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="value1" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="value2" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="value3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="value4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="value5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                   &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                   &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                   &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="extradescs" type="{http://swmud.pl/ns/swmud/1.0/area}extradescs"/>
 *                   &lt;element name="requirements">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="requirement" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="modifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="affects">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="affect" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="modifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="programs" type="{http://swmud.pl/ns/swmud/1.0/area}programs"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "objects", propOrder = {
    "object"
})
public class Objects {

    protected List<Objects.Object> object = new LinkedList<Objects.Object>();

    /**
     * Gets the value of the object property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the object property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Objects.Object }
     * 
     * 
     */
    public List<Objects.Object> getObject() {
        if (object == null) {
            object = new LinkedList<Objects.Object>();
        }
        return this.object;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="vnum" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
     *         &lt;element name="short" type="{http://swmud.pl/ns/swmud/1.0/area}short"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="actiondesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="extraflags" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="wearflags" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="layers" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="values">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="value0" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="value1" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="value2" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="value3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="value4" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="value5" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *         &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *         &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="extradescs" type="{http://swmud.pl/ns/swmud/1.0/area}extradescs"/>
     *         &lt;element name="requirements">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="requirement" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="modifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="affects">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="affect" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="modifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="programs" type="{http://swmud.pl/ns/swmud/1.0/area}programs"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vnum",
        "name",
        "_short",
        "description",
        "actiondesc",
        "type",
        "extraflags",
        "wearflags",
        "layers",
        "values",
        "weight",
        "cost",
        "gender",
        "level",
        "extradescs",
        "requirements",
        "affects",
        "programs"
    })
    public static class Object {

        @XmlElement(required = true)
        protected BigInteger vnum;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String name;
        @XmlElement(name = "short", required = true)
        protected Short _short;
        @XmlElement(required = true)
        protected String description;
        @XmlElement(required = true)
        protected String actiondesc;
        protected int type;
        protected long extraflags;
        protected long wearflags;
        protected int layers;
        @XmlElement(required = true)
        protected Objects.Object.Values values;
        protected long weight;
        protected long cost;
        protected long gender;
        protected short level;
        @XmlElement(required = true)
        protected Extradescs extradescs;
        @XmlElement(required = true)
        protected Objects.Object.Requirements requirements;
        @XmlElement(required = true)
        protected Objects.Object.Affects affects;
        @XmlElement(required = true)
        protected Programs programs;

        /**
         * Gets the value of the vnum property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getVnum() {
            return vnum;
        }

        /**
         * Sets the value of the vnum property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setVnum(BigInteger value) {
            this.vnum = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the short property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getShort() {
            return _short;
        }

        /**
         * Sets the value of the short property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setShort(Short value) {
            this._short = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the actiondesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActiondesc() {
            return actiondesc;
        }

        /**
         * Sets the value of the actiondesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActiondesc(String value) {
            this.actiondesc = value;
        }

        /**
         * Gets the value of the type property.
         * 
         */
        public int getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         */
        public void setType(int value) {
            this.type = value;
        }

        /**
         * Gets the value of the extraflags property.
         * 
         */
        public long getExtraflags() {
            return extraflags;
        }

        /**
         * Sets the value of the extraflags property.
         * 
         */
        public void setExtraflags(long value) {
            this.extraflags = value;
        }

        /**
         * Gets the value of the wearflags property.
         * 
         */
        public long getWearflags() {
            return wearflags;
        }

        /**
         * Sets the value of the wearflags property.
         * 
         */
        public void setWearflags(long value) {
            this.wearflags = value;
        }

        /**
         * Gets the value of the layers property.
         * 
         */
        public int getLayers() {
            return layers;
        }

        /**
         * Sets the value of the layers property.
         * 
         */
        public void setLayers(int value) {
            this.layers = value;
        }

        /**
         * Gets the value of the values property.
         * 
         * @return
         *     possible object is
         *     {@link Objects.Object.Values }
         *     
         */
        public Objects.Object.Values getValues() {
            return values;
        }

        /**
         * Sets the value of the values property.
         * 
         * @param value
         *     allowed object is
         *     {@link Objects.Object.Values }
         *     
         */
        public void setValues(Objects.Object.Values value) {
            this.values = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         */
        public long getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         */
        public void setWeight(long value) {
            this.weight = value;
        }

        /**
         * Gets the value of the cost property.
         * 
         */
        public long getCost() {
            return cost;
        }

        /**
         * Sets the value of the cost property.
         * 
         */
        public void setCost(long value) {
            this.cost = value;
        }

        /**
         * Gets the value of the gender property.
         * 
         */
        public long getGender() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         * 
         */
        public void setGender(long value) {
            this.gender = value;
        }

        /**
         * Gets the value of the level property.
         * 
         */
        public short getLevel() {
            return level;
        }

        /**
         * Sets the value of the level property.
         * 
         */
        public void setLevel(short value) {
            this.level = value;
        }

        /**
         * Gets the value of the extradescs property.
         * 
         * @return
         *     possible object is
         *     {@link Extradescs }
         *     
         */
        public Extradescs getExtradescs() {
            return extradescs;
        }

        /**
         * Sets the value of the extradescs property.
         * 
         * @param value
         *     allowed object is
         *     {@link Extradescs }
         *     
         */
        public void setExtradescs(Extradescs value) {
            this.extradescs = value;
        }

        /**
         * Gets the value of the requirements property.
         * 
         * @return
         *     possible object is
         *     {@link Objects.Object.Requirements }
         *     
         */
        public Objects.Object.Requirements getRequirements() {
            return requirements;
        }

        /**
         * Sets the value of the requirements property.
         * 
         * @param value
         *     allowed object is
         *     {@link Objects.Object.Requirements }
         *     
         */
        public void setRequirements(Objects.Object.Requirements value) {
            this.requirements = value;
        }

        /**
         * Gets the value of the affects property.
         * 
         * @return
         *     possible object is
         *     {@link Objects.Object.Affects }
         *     
         */
        public Objects.Object.Affects getAffects() {
            return affects;
        }

        /**
         * Sets the value of the affects property.
         * 
         * @param value
         *     allowed object is
         *     {@link Objects.Object.Affects }
         *     
         */
        public void setAffects(Objects.Object.Affects value) {
            this.affects = value;
        }

        /**
         * Gets the value of the programs property.
         * 
         * @return
         *     possible object is
         *     {@link Programs }
         *     
         */
        public Programs getPrograms() {
            return programs;
        }

        /**
         * Sets the value of the programs property.
         * 
         * @param value
         *     allowed object is
         *     {@link Programs }
         *     
         */
        public void setPrograms(Programs value) {
            this.programs = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="affect" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="modifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "affect"
        })
        public static class Affects {

            protected List<Objects.Object.Affects.Affect> affect = new LinkedList<Objects.Object.Affects.Affect>();

            /**
             * Gets the value of the affect property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the affect property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAffect().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Objects.Object.Affects.Affect }
             * 
             * 
             */
            public List<Objects.Object.Affects.Affect> getAffect() {
                if (affect == null) {
                    affect = new LinkedList<Objects.Object.Affects.Affect>();
                }
                return this.affect;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="modifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "location",
                "modifier"
            })
            public static class Affect {

                protected int location;
                protected int modifier;

                /**
                 * Gets the value of the location property.
                 * 
                 */
                public int getLocation() {
                    return location;
                }

                /**
                 * Sets the value of the location property.
                 * 
                 */
                public void setLocation(int value) {
                    this.location = value;
                }

                /**
                 * Gets the value of the modifier property.
                 * 
                 */
                public int getModifier() {
                    return modifier;
                }

                /**
                 * Sets the value of the modifier property.
                 * 
                 */
                public void setModifier(int value) {
                    this.modifier = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="requirement" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="modifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "requirement"
        })
        public static class Requirements {

            protected List<Objects.Object.Requirements.Requirement> requirement = new LinkedList<Objects.Object.Requirements.Requirement>();

            /**
             * Gets the value of the requirement property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the requirement property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRequirement().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Objects.Object.Requirements.Requirement }
             * 
             * 
             */
            public List<Objects.Object.Requirements.Requirement> getRequirement() {
                if (requirement == null) {
                    requirement = new LinkedList<Objects.Object.Requirements.Requirement>();
                }
                return this.requirement;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="modifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "location",
                "modifier",
                "type"
            })
            public static class Requirement {

                protected int location;
                protected int modifier;
                @XmlElement(required = true)
                protected String type;

                /**
                 * Gets the value of the location property.
                 * 
                 */
                public int getLocation() {
                    return location;
                }

                /**
                 * Sets the value of the location property.
                 * 
                 */
                public void setLocation(int value) {
                    this.location = value;
                }

                /**
                 * Gets the value of the modifier property.
                 * 
                 */
                public int getModifier() {
                    return modifier;
                }

                /**
                 * Sets the value of the modifier property.
                 * 
                 */
                public void setModifier(int value) {
                    this.modifier = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="value0" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="value1" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="value2" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="value3" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="value4" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="value5" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value0",
            "value1",
            "value2",
            "value3",
            "value4",
            "value5"
        })
        public static class Values {

            protected int value0;
            protected int value1;
            protected int value2;
            @XmlElement(required = true)
            protected String value3;
            @XmlElement(required = true)
            protected String value4;
            @XmlElement(required = true)
            protected String value5;

            /**
             * Gets the value of the value0 property.
             * 
             */
            public int getValue0() {
                return value0;
            }

            /**
             * Sets the value of the value0 property.
             * 
             */
            public void setValue0(int value) {
                this.value0 = value;
            }

            /**
             * Gets the value of the value1 property.
             * 
             */
            public int getValue1() {
                return value1;
            }

            /**
             * Sets the value of the value1 property.
             * 
             */
            public void setValue1(int value) {
                this.value1 = value;
            }

            /**
             * Gets the value of the value2 property.
             * 
             */
            public int getValue2() {
                return value2;
            }

            /**
             * Sets the value of the value2 property.
             * 
             */
            public void setValue2(int value) {
                this.value2 = value;
            }

            /**
             * Gets the value of the value3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue3() {
                return value3;
            }

            /**
             * Sets the value of the value3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue3(String value) {
                this.value3 = value;
            }

            /**
             * Gets the value of the value4 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue4() {
                return value4;
            }

            /**
             * Sets the value of the value4 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue4(String value) {
                this.value4 = value;
            }

            /**
             * Gets the value of the value5 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue5() {
                return value5;
            }

            /**
             * Sets the value of the value5 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue5(String value) {
                this.value5 = value;
            }

        }

    }

}
