//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.25 at 07:22:39 PM CET 
//


package pl.swmud.ns.swmud._1_0.area;

import java.math.BigInteger;
import java.util.LinkedList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for rooms complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rooms">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="room" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="vnum" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nightdesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="light" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="flags" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="sector" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="teledelay" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="televnum" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="tunnel" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="exits">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="exit" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                       &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="keyword" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *                                       &lt;element name="flags" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                       &lt;element name="vnum" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                                       &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="extradescs" type="{http://swmud.pl/ns/swmud/1.0/area}extradescs"/>
 *                   &lt;element name="programs" type="{http://swmud.pl/ns/swmud/1.0/area}programs"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rooms", propOrder = {
    "room"
})
public class Rooms {

    protected List<Rooms.Room> room = new LinkedList<Rooms.Room>();

    /**
     * Gets the value of the room property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the room property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rooms.Room }
     * 
     * 
     */
    public List<Rooms.Room> getRoom() {
        if (room == null) {
            room = new LinkedList<Rooms.Room>();
        }
        return this.room;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="vnum" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="nightdesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="light" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="flags" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="sector" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="teledelay" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="televnum" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="tunnel" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="exits">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="exit" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="keyword" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
     *                             &lt;element name="flags" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                             &lt;element name="vnum" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *                             &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="extradescs" type="{http://swmud.pl/ns/swmud/1.0/area}extradescs"/>
     *         &lt;element name="programs" type="{http://swmud.pl/ns/swmud/1.0/area}programs"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vnum",
        "name",
        "description",
        "nightdesc",
        "light",
        "flags",
        "sector",
        "teledelay",
        "televnum",
        "tunnel",
        "exits",
        "extradescs",
        "programs"
    })
    public static class Room {

        @XmlElement(required = true)
        protected BigInteger vnum;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String name;
        @XmlElement(required = true)
        protected String description;
        protected String nightdesc;
        protected short light;
        protected long flags;
        protected int sector;
        @XmlElement(required = true)
        protected BigInteger teledelay;
        @XmlElement(required = true)
        protected BigInteger televnum;
        @XmlElement(required = true)
        protected BigInteger tunnel;
        @XmlElement(required = true)
        protected Rooms.Room.Exits exits;
        @XmlElement(required = true)
        protected Extradescs extradescs;
        @XmlElement(required = true)
        protected Programs programs;

        /**
         * Gets the value of the vnum property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getVnum() {
            return vnum;
        }

        /**
         * Sets the value of the vnum property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setVnum(BigInteger value) {
            this.vnum = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the nightdesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNightdesc() {
            return nightdesc;
        }

        /**
         * Sets the value of the nightdesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNightdesc(String value) {
            this.nightdesc = value;
        }

        /**
         * Gets the value of the light property.
         * 
         */
        public short getLight() {
            return light;
        }

        /**
         * Sets the value of the light property.
         * 
         */
        public void setLight(short value) {
            this.light = value;
        }

        /**
         * Gets the value of the flags property.
         * 
         */
        public long getFlags() {
            return flags;
        }

        /**
         * Sets the value of the flags property.
         * 
         */
        public void setFlags(long value) {
            this.flags = value;
        }

        /**
         * Gets the value of the sector property.
         * 
         */
        public int getSector() {
            return sector;
        }

        /**
         * Sets the value of the sector property.
         * 
         */
        public void setSector(int value) {
            this.sector = value;
        }

        /**
         * Gets the value of the teledelay property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTeledelay() {
            return teledelay;
        }

        /**
         * Sets the value of the teledelay property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTeledelay(BigInteger value) {
            this.teledelay = value;
        }

        /**
         * Gets the value of the televnum property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTelevnum() {
            return televnum;
        }

        /**
         * Sets the value of the televnum property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTelevnum(BigInteger value) {
            this.televnum = value;
        }

        /**
         * Gets the value of the tunnel property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTunnel() {
            return tunnel;
        }

        /**
         * Sets the value of the tunnel property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTunnel(BigInteger value) {
            this.tunnel = value;
        }

        /**
         * Gets the value of the exits property.
         * 
         * @return
         *     possible object is
         *     {@link Rooms.Room.Exits }
         *     
         */
        public Rooms.Room.Exits getExits() {
            return exits;
        }

        /**
         * Sets the value of the exits property.
         * 
         * @param value
         *     allowed object is
         *     {@link Rooms.Room.Exits }
         *     
         */
        public void setExits(Rooms.Room.Exits value) {
            this.exits = value;
        }

        /**
         * Gets the value of the extradescs property.
         * 
         * @return
         *     possible object is
         *     {@link Extradescs }
         *     
         */
        public Extradescs getExtradescs() {
            return extradescs;
        }

        /**
         * Sets the value of the extradescs property.
         * 
         * @param value
         *     allowed object is
         *     {@link Extradescs }
         *     
         */
        public void setExtradescs(Extradescs value) {
            this.extradescs = value;
        }

        /**
         * Gets the value of the programs property.
         * 
         * @return
         *     possible object is
         *     {@link Programs }
         *     
         */
        public Programs getPrograms() {
            return programs;
        }

        /**
         * Sets the value of the programs property.
         * 
         * @param value
         *     allowed object is
         *     {@link Programs }
         *     
         */
        public void setPrograms(Programs value) {
            this.programs = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="exit" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="keyword" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
         *                   &lt;element name="flags" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                   &lt;element name="vnum" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
         *                   &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "exit"
        })
        public static class Exits {

            protected List<Rooms.Room.Exits.Exit> exit = new LinkedList<Rooms.Room.Exits.Exit>();

            /**
             * Gets the value of the exit property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the exit property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getExit().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Rooms.Room.Exits.Exit }
             * 
             * 
             */
            public List<Rooms.Room.Exits.Exit> getExit() {
                if (exit == null) {
                    exit = new LinkedList<Rooms.Room.Exits.Exit>();
                }
                return this.exit;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="keyword" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
             *         &lt;element name="flags" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *         &lt;element name="vnum" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
             *         &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "direction",
                "description",
                "keyword",
                "flags",
                "key",
                "vnum",
                "distance"
            })
            public static class Exit {

                protected short direction;
                @XmlElement(required = true)
                protected String description;
                @XmlElement(required = true)
                @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                protected String keyword;
                protected long flags;
                @XmlElement(required = true)
                protected BigInteger key;
                @XmlElement(required = true)
                protected BigInteger vnum;
                protected int distance;

                /**
                 * Gets the value of the direction property.
                 * 
                 */
                public short getDirection() {
                    return direction;
                }

                /**
                 * Sets the value of the direction property.
                 * 
                 */
                public void setDirection(short value) {
                    this.direction = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

                /**
                 * Gets the value of the keyword property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getKeyword() {
                    return keyword;
                }

                /**
                 * Sets the value of the keyword property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setKeyword(String value) {
                    this.keyword = value;
                }

                /**
                 * Gets the value of the flags property.
                 * 
                 */
                public long getFlags() {
                    return flags;
                }

                /**
                 * Sets the value of the flags property.
                 * 
                 */
                public void setFlags(long value) {
                    this.flags = value;
                }

                /**
                 * Gets the value of the key property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getKey() {
                    return key;
                }

                /**
                 * Sets the value of the key property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setKey(BigInteger value) {
                    this.key = value;
                }

                /**
                 * Gets the value of the vnum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getVnum() {
                    return vnum;
                }

                /**
                 * Sets the value of the vnum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setVnum(BigInteger value) {
                    this.vnum = value;
                }

                /**
                 * Gets the value of the distance property.
                 * 
                 */
                public int getDistance() {
                    return distance;
                }

                /**
                 * Sets the value of the distance property.
                 * 
                 */
                public void setDistance(int value) {
                    this.distance = value;
                }

            }

        }

    }

}
