//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.25 at 07:22:39 PM CET 
//


package pl.swmud.ns.swmud._1_0.area;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for sectionr complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sectionr">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="speaks" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="speaking" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *         &lt;element name="numattacks" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sectionr", propOrder = {
    "height",
    "weight",
    "speaks",
    "speaking",
    "numattacks"
})
public class Sectionr {

    protected short height;
    protected short weight;
    protected long speaks;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String speaking;
    protected short numattacks;

    /**
     * Gets the value of the height property.
     * 
     */
    public short getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     */
    public void setHeight(short value) {
        this.height = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     */
    public short getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     */
    public void setWeight(short value) {
        this.weight = value;
    }

    /**
     * Gets the value of the speaks property.
     * 
     */
    public long getSpeaks() {
        return speaks;
    }

    /**
     * Sets the value of the speaks property.
     * 
     */
    public void setSpeaks(long value) {
        this.speaks = value;
    }

    /**
     * Gets the value of the speaking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeaking() {
        return speaking;
    }

    /**
     * Sets the value of the speaking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeaking(String value) {
        this.speaking = value;
    }

    /**
     * Gets the value of the numattacks property.
     * 
     */
    public short getNumattacks() {
        return numattacks;
    }

    /**
     * Sets the value of the numattacks property.
     * 
     */
    public void setNumattacks(short value) {
        this.numattacks = value;
    }

}
