//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.25 at 07:22:39 PM CET 
//


package pl.swmud.ns.swmud._1_0.area;

import java.math.BigInteger;
import java.util.LinkedList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for shops complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="shops">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="shop" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="keeper" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                   &lt;element name="types">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="type0" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="type1" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="type2" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="type3" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="type4" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="profitbuy" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="profitsell" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="open" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="close" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="flags" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "shops", propOrder = {
    "shop"
})
public class Shops {

    protected List<Shops.Shop> shop = new LinkedList<Shops.Shop>();

    /**
     * Gets the value of the shop property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shop property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShop().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Shops.Shop }
     * 
     * 
     */
    public List<Shops.Shop> getShop() {
        if (shop == null) {
            shop = new LinkedList<Shops.Shop>();
        }
        return this.shop;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="keeper" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *         &lt;element name="types">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="type0" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                   &lt;element name="type1" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                   &lt;element name="type2" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                   &lt;element name="type3" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                   &lt;element name="type4" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="profitbuy" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="profitsell" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="open" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="close" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="flags" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "keeper",
        "types",
        "profitbuy",
        "profitsell",
        "open",
        "close",
        "flags"
    })
    public static class Shop {

        @XmlElement(required = true)
        protected BigInteger keeper;
        @XmlElement(required = true)
        protected Shops.Shop.Types types;
        protected int profitbuy;
        protected int profitsell;
        protected short open;
        protected short close;
        protected long flags;

        /**
         * Gets the value of the keeper property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getKeeper() {
            return keeper;
        }

        /**
         * Sets the value of the keeper property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setKeeper(BigInteger value) {
            this.keeper = value;
        }

        /**
         * Gets the value of the types property.
         * 
         * @return
         *     possible object is
         *     {@link Shops.Shop.Types }
         *     
         */
        public Shops.Shop.Types getTypes() {
            return types;
        }

        /**
         * Sets the value of the types property.
         * 
         * @param value
         *     allowed object is
         *     {@link Shops.Shop.Types }
         *     
         */
        public void setTypes(Shops.Shop.Types value) {
            this.types = value;
        }

        /**
         * Gets the value of the profitbuy property.
         * 
         */
        public int getProfitbuy() {
            return profitbuy;
        }

        /**
         * Sets the value of the profitbuy property.
         * 
         */
        public void setProfitbuy(int value) {
            this.profitbuy = value;
        }

        /**
         * Gets the value of the profitsell property.
         * 
         */
        public int getProfitsell() {
            return profitsell;
        }

        /**
         * Sets the value of the profitsell property.
         * 
         */
        public void setProfitsell(int value) {
            this.profitsell = value;
        }

        /**
         * Gets the value of the open property.
         * 
         */
        public short getOpen() {
            return open;
        }

        /**
         * Sets the value of the open property.
         * 
         */
        public void setOpen(short value) {
            this.open = value;
        }

        /**
         * Gets the value of the close property.
         * 
         */
        public short getClose() {
            return close;
        }

        /**
         * Sets the value of the close property.
         * 
         */
        public void setClose(short value) {
            this.close = value;
        }

        /**
         * Gets the value of the flags property.
         * 
         */
        public long getFlags() {
            return flags;
        }

        /**
         * Sets the value of the flags property.
         * 
         */
        public void setFlags(long value) {
            this.flags = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="type0" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *         &lt;element name="type1" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *         &lt;element name="type2" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *         &lt;element name="type3" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *         &lt;element name="type4" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "type0",
            "type1",
            "type2",
            "type3",
            "type4"
        })
        public static class Types {

            protected short type0;
            protected short type1;
            protected short type2;
            protected short type3;
            protected short type4;

            /**
             * Gets the value of the type0 property.
             * 
             */
            public short getType0() {
                return type0;
            }

            /**
             * Sets the value of the type0 property.
             * 
             */
            public void setType0(short value) {
                this.type0 = value;
            }

            /**
             * Gets the value of the type1 property.
             * 
             */
            public short getType1() {
                return type1;
            }

            /**
             * Sets the value of the type1 property.
             * 
             */
            public void setType1(short value) {
                this.type1 = value;
            }

            /**
             * Gets the value of the type2 property.
             * 
             */
            public short getType2() {
                return type2;
            }

            /**
             * Sets the value of the type2 property.
             * 
             */
            public void setType2(short value) {
                this.type2 = value;
            }

            /**
             * Gets the value of the type3 property.
             * 
             */
            public short getType3() {
                return type3;
            }

            /**
             * Sets the value of the type3 property.
             * 
             */
            public void setType3(short value) {
                this.type3 = value;
            }

            /**
             * Gets the value of the type4 property.
             * 
             */
            public short getType4() {
                return type4;
            }

            /**
             * Sets the value of the type4 property.
             * 
             */
            public void setType4(short value) {
                this.type4 = value;
            }

        }

    }

}
