//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.25 at 07:22:39 PM CET 
//


package pl.swmud.ns.swmud._1_0.area;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for short complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="short">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inflect0" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *         &lt;element name="inflect1" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *         &lt;element name="inflect2" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *         &lt;element name="inflect3" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *         &lt;element name="inflect4" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *         &lt;element name="inflect5" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "short", propOrder = {
    "inflect0",
    "inflect1",
    "inflect2",
    "inflect3",
    "inflect4",
    "inflect5"
})
public class Short {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inflect0;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inflect1;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inflect2;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inflect3;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inflect4;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inflect5;

    /**
     * Gets the value of the inflect0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInflect0() {
        return inflect0;
    }

    /**
     * Sets the value of the inflect0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInflect0(String value) {
        this.inflect0 = value;
    }

    /**
     * Gets the value of the inflect1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInflect1() {
        return inflect1;
    }

    /**
     * Sets the value of the inflect1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInflect1(String value) {
        this.inflect1 = value;
    }

    /**
     * Gets the value of the inflect2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInflect2() {
        return inflect2;
    }

    /**
     * Sets the value of the inflect2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInflect2(String value) {
        this.inflect2 = value;
    }

    /**
     * Gets the value of the inflect3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInflect3() {
        return inflect3;
    }

    /**
     * Sets the value of the inflect3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInflect3(String value) {
        this.inflect3 = value;
    }

    /**
     * Gets the value of the inflect4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInflect4() {
        return inflect4;
    }

    /**
     * Sets the value of the inflect4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInflect4(String value) {
        this.inflect4 = value;
    }

    /**
     * Gets the value of the inflect5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInflect5() {
        return inflect5;
    }

    /**
     * Sets the value of the inflect5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInflect5(String value) {
        this.inflect5 = value;
    }

}
