//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.14 at 09:54:43 PM CET 
//


package pl.swmud.ns.swaedit.exits;

import java.util.LinkedList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for exits complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="exits">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="exit" type="{http://swmud.pl/ns/swaedit/exits}exit"/>
 *       &lt;/sequence>
 *       &lt;attribute name="gridColumns" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" default="3" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "exits", propOrder = {
    "exit"
})
@XmlRootElement
public class Exits {

    protected List<Exit> exit = new LinkedList<Exit>();
    @XmlAttribute
    protected Short gridColumns;

    /**
     * Gets the value of the exit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Exit }
     * 
     * 
     */
    public List<Exit> getExit() {
        if (exit == null) {
            exit = new LinkedList<Exit>();
        }
        return this.exit;
    }

    /**
     * Gets the value of the gridColumns property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public short getGridColumns() {
        if (gridColumns == null) {
            return ((short) 3);
        } else {
            return gridColumns;
        }
    }

    /**
     * Sets the value of the gridColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setGridColumns(Short value) {
        this.gridColumns = value;
    }

}
