//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.23 at 01:05:44 PM CET 
//


package pl.swmud.ns.swaedit.usprotocol;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.swmud.ns.swaedit.usprotocol package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Usprotocol_QNAME = new QName("http://swmud.pl/ns/swaedit/usprotocol", "usprotocol");
    private final static QName _RequestFile_QNAME = new QName("http://swmud.pl/ns/swaedit/usprotocol", "file");
    private final static QName _RequestMessage_QNAME = new QName("http://swmud.pl/ns/swaedit/usprotocol", "message");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.swmud.ns.swaedit.usprotocol
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Messages }
     * 
     */
    public Messages createMessages() {
        return new Messages();
    }

    /**
     * Create an instance of {@link Files }
     * 
     */
    public Files createFiles() {
        return new Files();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link Usprotocol }
     * 
     */
    public Usprotocol createUsprotocol() {
        return new Usprotocol();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Usprotocol }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://swmud.pl/ns/swaedit/usprotocol", name = "usprotocol")
    public JAXBElement<Usprotocol> createUsprotocol(Usprotocol value) {
        return new JAXBElement<Usprotocol>(_Usprotocol_QNAME, Usprotocol.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://swmud.pl/ns/swaedit/usprotocol", name = "file", scope = Request.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createRequestFile(String value) {
        return new JAXBElement<String>(_RequestFile_QNAME, String.class, Request.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://swmud.pl/ns/swaedit/usprotocol", name = "message", scope = Request.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createRequestMessage(String value) {
        return new JAXBElement<String>(_RequestMessage_QNAME, String.class, Request.class, value);
    }

}
