//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.17 at 12:51:30 PM CET 
//


package pl.swmud.ns.swaedit.flags;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.swmud.ns.swaedit.flags package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Flags_QNAME = new QName("http://swmud.pl/ns/swaedit/flags", "flags");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.swmud.ns.swaedit.flags
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Flags }
     * 
     */
    public Flags createFlags() {
        return new Flags();
    }

    /**
     * Create an instance of {@link Flag }
     * 
     */
    public Flag createFlag() {
        return new Flag();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flags }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://swmud.pl/ns/swaedit/flags", name = "flags")
    public JAXBElement<Flags> createFlags(Flags value) {
        return new JAXBElement<Flags>(_Flags_QNAME, Flags.class, null, value);
    }

}
