//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.17 at 03:26:21 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://swmud.pl/ns/swaedit/types", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.swmud.ns.swaedit.types;
