//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.06 at 02:56:48 PM CET 
//


package pl.swmud.ns.swaedit.itemtypes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.swmud.ns.swaedit.itemtypes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Itemtypes_QNAME = new QName("http://swmud.pl/ns/swaedit/itemtypes", "itemtypes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.swmud.ns.swaedit.itemtypes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link Subvalue }
     * 
     */
    public Subvalue createSubvalue() {
        return new Subvalue();
    }

    /**
     * Create an instance of {@link Itemtype }
     * 
     */
    public Itemtype createItemtype() {
        return new Itemtype();
    }

    /**
     * Create an instance of {@link Subvalues }
     * 
     */
    public Subvalues createSubvalues() {
        return new Subvalues();
    }

    /**
     * Create an instance of {@link Itemtypes }
     * 
     */
    public Itemtypes createItemtypes() {
        return new Itemtypes();
    }

    /**
     * Create an instance of {@link Values }
     * 
     */
    public Values createValues() {
        return new Values();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Itemtypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://swmud.pl/ns/swaedit/itemtypes", name = "itemtypes")
    public JAXBElement<Itemtypes> createItemtypes(Itemtypes value) {
        return new JAXBElement<Itemtypes>(_Itemtypes_QNAME, Itemtypes.class, null, value);
    }

}
