//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.08 at 07:11:14 PM CET 
//


package pl.swmud.ns.swaedit.highlighter;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.swmud.ns.swaedit.highlighter package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WordsWord_QNAME = new QName("http://swmud.pl/ns/swaedit/highlighter", "word");
    private final static QName _Highlighter_QNAME = new QName("http://swmud.pl/ns/swaedit/highlighter", "highlighter");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.swmud.ns.swaedit.highlighter
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Words }
     * 
     */
    public Words createWords() {
        return new Words();
    }

    /**
     * Create an instance of {@link Highlighter }
     * 
     */
    public Highlighter createHighlighter() {
        return new Highlighter();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://swmud.pl/ns/swaedit/highlighter", name = "word", scope = Words.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createWordsWord(String value) {
        return new JAXBElement<String>(_WordsWord_QNAME, String.class, Words.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Highlighter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://swmud.pl/ns/swaedit/highlighter", name = "highlighter")
    public JAXBElement<Highlighter> createHighlighter(Highlighter value) {
        return new JAXBElement<Highlighter>(_Highlighter_QNAME, Highlighter.class, null, value);
    }

}
