//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.08 at 07:11:14 PM CET 
//


package pl.swmud.ns.swaedit.highlighter;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="flowInstruction"/>
 *     &lt;enumeration value="progCommand"/>
 *     &lt;enumeration value="ifCheck"/>
 *     &lt;enumeration value="variable"/>
 *     &lt;enumeration value="ratmVariable"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum Type {

    @XmlEnumValue("flowInstruction")
    FLOW_INSTRUCTION("flowInstruction"),
    @XmlEnumValue("progCommand")
    PROG_COMMAND("progCommand"),
    @XmlEnumValue("ifCheck")
    IF_CHECK("ifCheck"),
    @XmlEnumValue("variable")
    VARIABLE("variable"),
    @XmlEnumValue("ratmVariable")
    RATM_VARIABLE("ratmVariable");
    private final String value;

    Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Type fromValue(String v) {
        for (Type c: Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
