//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.25 at 07:22:39 PM CET 
//


package pl.swmud.ns.swmud._1_0.area;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.swmud.ns.swmud._1_0.area package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Area_QNAME = new QName("http://swmud.pl/ns/swmud/1.0/area", "area");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.swmud.ns.swmud._1_0.area
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Shops }
     * 
     */
    public Shops createShops() {
        return new Shops();
    }

    /**
     * Create an instance of {@link Head.Economy }
     * 
     */
    public Head.Economy createHeadEconomy() {
        return new Head.Economy();
    }

    /**
     * Create an instance of {@link Shops.Shop }
     * 
     */
    public Shops.Shop createShopsShop() {
        return new Shops.Shop();
    }

    /**
     * Create an instance of {@link Mobiles }
     * 
     */
    public Mobiles createMobiles() {
        return new Mobiles();
    }

    /**
     * Create an instance of {@link Rooms.Room }
     * 
     */
    public Rooms.Room createRoomsRoom() {
        return new Rooms.Room();
    }

    /**
     * Create an instance of {@link Resets }
     * 
     */
    public Resets createResets() {
        return new Resets();
    }

    /**
     * Create an instance of {@link Repairs.Repair.Types }
     * 
     */
    public Repairs.Repair.Types createRepairsRepairTypes() {
        return new Repairs.Repair.Types();
    }

    /**
     * Create an instance of {@link Objects.Object }
     * 
     */
    public Objects.Object createObjectsObject() {
        return new Objects.Object();
    }

    /**
     * Create an instance of {@link Repairs.Repair }
     * 
     */
    public Repairs.Repair createRepairsRepair() {
        return new Repairs.Repair();
    }

    /**
     * Create an instance of {@link Repairs }
     * 
     */
    public Repairs createRepairs() {
        return new Repairs();
    }

    /**
     * Create an instance of {@link Extradescs.Extradesc }
     * 
     */
    public Extradescs.Extradesc createExtradescsExtradesc() {
        return new Extradescs.Extradesc();
    }

    /**
     * Create an instance of {@link Sectionv }
     * 
     */
    public Sectionv createSectionv() {
        return new Sectionv();
    }

    /**
     * Create an instance of {@link Objects.Object.Affects.Affect }
     * 
     */
    public Objects.Object.Affects.Affect createObjectsObjectAffectsAffect() {
        return new Objects.Object.Affects.Affect();
    }

    /**
     * Create an instance of {@link Resets.Reset }
     * 
     */
    public Resets.Reset createResetsReset() {
        return new Resets.Reset();
    }

    /**
     * Create an instance of {@link Objects.Object.Values }
     * 
     */
    public Objects.Object.Values createObjectsObjectValues() {
        return new Objects.Object.Values();
    }

    /**
     * Create an instance of {@link Sectionx }
     * 
     */
    public Sectionx createSectionx() {
        return new Sectionx();
    }

    /**
     * Create an instance of {@link Sectiona }
     * 
     */
    public Sectiona createSectiona() {
        return new Sectiona();
    }

    /**
     * Create an instance of {@link Shops.Shop.Types }
     * 
     */
    public Shops.Shop.Types createShopsShopTypes() {
        return new Shops.Shop.Types();
    }

    /**
     * Create an instance of {@link Head.Vnums }
     * 
     */
    public Head.Vnums createHeadVnums() {
        return new Head.Vnums();
    }

    /**
     * Create an instance of {@link Mobiles.Mobile }
     * 
     */
    public Mobiles.Mobile createMobilesMobile() {
        return new Mobiles.Mobile();
    }

    /**
     * Create an instance of {@link Objects.Object.Affects }
     * 
     */
    public Objects.Object.Affects createObjectsObjectAffects() {
        return new Objects.Object.Affects();
    }

    /**
     * Create an instance of {@link Programs.Program }
     * 
     */
    public Programs.Program createProgramsProgram() {
        return new Programs.Program();
    }

    /**
     * Create an instance of {@link Extradescs }
     * 
     */
    public Extradescs createExtradescs() {
        return new Extradescs();
    }

    /**
     * Create an instance of {@link Sections }
     * 
     */
    public Sections createSections() {
        return new Sections();
    }

    /**
     * Create an instance of {@link Rooms.Room.Exits }
     * 
     */
    public Rooms.Room.Exits createRoomsRoomExits() {
        return new Rooms.Room.Exits();
    }

    /**
     * Create an instance of {@link Head.Ranges }
     * 
     */
    public Head.Ranges createHeadRanges() {
        return new Head.Ranges();
    }

    /**
     * Create an instance of {@link Head.Reset }
     * 
     */
    public Head.Reset createHeadReset() {
        return new Head.Reset();
    }

    /**
     * Create an instance of {@link Objects }
     * 
     */
    public Objects createObjects() {
        return new Objects();
    }

    /**
     * Create an instance of {@link Specials.Special }
     * 
     */
    public Specials.Special createSpecialsSpecial() {
        return new Specials.Special();
    }

    /**
     * Create an instance of {@link Short }
     * 
     */
    public Short createShort() {
        return new Short();
    }

    /**
     * Create an instance of {@link Sectionr }
     * 
     */
    public Sectionr createSectionr() {
        return new Sectionr();
    }

    /**
     * Create an instance of {@link Objects.Object.Requirements.Requirement }
     * 
     */
    public Objects.Object.Requirements.Requirement createObjectsObjectRequirementsRequirement() {
        return new Objects.Object.Requirements.Requirement();
    }

    /**
     * Create an instance of {@link Head }
     * 
     */
    public Head createHead() {
        return new Head();
    }

    /**
     * Create an instance of {@link Rooms }
     * 
     */
    public Rooms createRooms() {
        return new Rooms();
    }

    /**
     * Create an instance of {@link Sectiont }
     * 
     */
    public Sectiont createSectiont() {
        return new Sectiont();
    }

    /**
     * Create an instance of {@link Programs }
     * 
     */
    public Programs createPrograms() {
        return new Programs();
    }

    /**
     * Create an instance of {@link Specials }
     * 
     */
    public Specials createSpecials() {
        return new Specials();
    }

    /**
     * Create an instance of {@link Rooms.Room.Exits.Exit }
     * 
     */
    public Rooms.Room.Exits.Exit createRoomsRoomExitsExit() {
        return new Rooms.Room.Exits.Exit();
    }

    /**
     * Create an instance of {@link Area }
     * 
     */
    public Area createArea() {
        return new Area();
    }

    /**
     * Create an instance of {@link Objects.Object.Requirements }
     * 
     */
    public Objects.Object.Requirements createObjectsObjectRequirements() {
        return new Objects.Object.Requirements();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Area }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://swmud.pl/ns/swmud/1.0/area", name = "area")
    public JAXBElement<Area> createArea(Area value) {
        return new JAXBElement<Area>(_Area_QNAME, Area.class, null, value);
    }

}
