//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.25 at 07:22:39 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://swmud.pl/ns/swmud/1.0/area", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.swmud.ns.swmud._1_0.area;
