//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.25 at 07:22:39 PM CET 
//


package pl.swmud.ns.swmud._1_0.area;

import java.math.BigInteger;
import java.util.LinkedList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for resets complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resets">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reset" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="command">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *                         &lt;pattern value="[MOPGEHBTDRC]"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="extra" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="arg1" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="arg2" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="arg3" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="arg4" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resets", propOrder = {
    "reset"
})
public class Resets {

    protected List<Resets.Reset> reset = new LinkedList<Resets.Reset>();

    /**
     * Gets the value of the reset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Resets.Reset }
     * 
     * 
     */
    public List<Resets.Reset> getReset() {
        if (reset == null) {
            reset = new LinkedList<Resets.Reset>();
        }
        return this.reset;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="command">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
     *               &lt;pattern value="[MOPGEHBTDRC]"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="extra" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="arg1" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="arg2" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="arg3" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="arg4" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "command",
        "extra",
        "arg1",
        "arg2",
        "arg3",
        "arg4"
    })
    public static class Reset {

        @XmlElement(required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String command;
        @XmlElement(required = true)
        protected BigInteger extra;
        @XmlElement(required = true)
        protected BigInteger arg1;
        @XmlElement(required = true)
        protected BigInteger arg2;
        @XmlElement(required = true)
        protected BigInteger arg3;
        @XmlElement(required = true)
        protected BigInteger arg4;

        /**
         * Gets the value of the command property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCommand() {
            return command;
        }

        /**
         * Sets the value of the command property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCommand(String value) {
            this.command = value;
        }

        /**
         * Gets the value of the extra property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getExtra() {
            return extra;
        }

        /**
         * Sets the value of the extra property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setExtra(BigInteger value) {
            this.extra = value;
        }

        /**
         * Gets the value of the arg1 property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getArg1() {
            return arg1;
        }

        /**
         * Sets the value of the arg1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setArg1(BigInteger value) {
            this.arg1 = value;
        }

        /**
         * Gets the value of the arg2 property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getArg2() {
            return arg2;
        }

        /**
         * Sets the value of the arg2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setArg2(BigInteger value) {
            this.arg2 = value;
        }

        /**
         * Gets the value of the arg3 property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getArg3() {
            return arg3;
        }

        /**
         * Sets the value of the arg3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setArg3(BigInteger value) {
            this.arg3 = value;
        }

        /**
         * Gets the value of the arg4 property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getArg4() {
            return arg4;
        }

        /**
         * Sets the value of the arg4 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setArg4(BigInteger value) {
            this.arg4 = value;
        }

    }

}
