//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.25 at 07:22:39 PM CET 
//


package pl.swmud.ns.swmud._1_0.area;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sectionx complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sectionx">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hitroll" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="damroll" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="xflags" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="resistant" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="immune" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="susceptible" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="attacks" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="defenses" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sectionx", propOrder = {
    "hitroll",
    "damroll",
    "xflags",
    "resistant",
    "immune",
    "susceptible",
    "attacks",
    "defenses"
})
public class Sectionx {

    protected short hitroll;
    protected short damroll;
    protected long xflags;
    protected long resistant;
    protected long immune;
    protected long susceptible;
    protected long attacks;
    protected long defenses;

    /**
     * Gets the value of the hitroll property.
     * 
     */
    public short getHitroll() {
        return hitroll;
    }

    /**
     * Sets the value of the hitroll property.
     * 
     */
    public void setHitroll(short value) {
        this.hitroll = value;
    }

    /**
     * Gets the value of the damroll property.
     * 
     */
    public short getDamroll() {
        return damroll;
    }

    /**
     * Sets the value of the damroll property.
     * 
     */
    public void setDamroll(short value) {
        this.damroll = value;
    }

    /**
     * Gets the value of the xflags property.
     * 
     */
    public long getXflags() {
        return xflags;
    }

    /**
     * Sets the value of the xflags property.
     * 
     */
    public void setXflags(long value) {
        this.xflags = value;
    }

    /**
     * Gets the value of the resistant property.
     * 
     */
    public long getResistant() {
        return resistant;
    }

    /**
     * Sets the value of the resistant property.
     * 
     */
    public void setResistant(long value) {
        this.resistant = value;
    }

    /**
     * Gets the value of the immune property.
     * 
     */
    public long getImmune() {
        return immune;
    }

    /**
     * Sets the value of the immune property.
     * 
     */
    public void setImmune(long value) {
        this.immune = value;
    }

    /**
     * Gets the value of the susceptible property.
     * 
     */
    public long getSusceptible() {
        return susceptible;
    }

    /**
     * Sets the value of the susceptible property.
     * 
     */
    public void setSusceptible(long value) {
        this.susceptible = value;
    }

    /**
     * Gets the value of the attacks property.
     * 
     */
    public long getAttacks() {
        return attacks;
    }

    /**
     * Sets the value of the attacks property.
     * 
     */
    public void setAttacks(long value) {
        this.attacks = value;
    }

    /**
     * Gets the value of the defenses property.
     * 
     */
    public long getDefenses() {
        return defenses;
    }

    /**
     * Sets the value of the defenses property.
     * 
     */
    public void setDefenses(long value) {
        this.defenses = value;
    }

}
