//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.25 at 07:22:39 PM CET 
//


package pl.swmud.ns.swmud._1_0.area;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sectiont complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sectiont">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="thac0" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="ac" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="hitnodice" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="hitsizedice" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="hitplus" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="damnodice" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="damsizedice" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="damplus" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sectiont", propOrder = {
    "thac0",
    "ac",
    "hitnodice",
    "hitsizedice",
    "hitplus",
    "damnodice",
    "damsizedice",
    "damplus"
})
public class Sectiont {

    protected short thac0;
    protected short ac;
    protected int hitnodice;
    protected int hitsizedice;
    protected int hitplus;
    protected int damnodice;
    protected int damsizedice;
    protected int damplus;

    /**
     * Gets the value of the thac0 property.
     * 
     */
    public short getThac0() {
        return thac0;
    }

    /**
     * Sets the value of the thac0 property.
     * 
     */
    public void setThac0(short value) {
        this.thac0 = value;
    }

    /**
     * Gets the value of the ac property.
     * 
     */
    public short getAc() {
        return ac;
    }

    /**
     * Sets the value of the ac property.
     * 
     */
    public void setAc(short value) {
        this.ac = value;
    }

    /**
     * Gets the value of the hitnodice property.
     * 
     */
    public int getHitnodice() {
        return hitnodice;
    }

    /**
     * Sets the value of the hitnodice property.
     * 
     */
    public void setHitnodice(int value) {
        this.hitnodice = value;
    }

    /**
     * Gets the value of the hitsizedice property.
     * 
     */
    public int getHitsizedice() {
        return hitsizedice;
    }

    /**
     * Sets the value of the hitsizedice property.
     * 
     */
    public void setHitsizedice(int value) {
        this.hitsizedice = value;
    }

    /**
     * Gets the value of the hitplus property.
     * 
     */
    public int getHitplus() {
        return hitplus;
    }

    /**
     * Sets the value of the hitplus property.
     * 
     */
    public void setHitplus(int value) {
        this.hitplus = value;
    }

    /**
     * Gets the value of the damnodice property.
     * 
     */
    public int getDamnodice() {
        return damnodice;
    }

    /**
     * Sets the value of the damnodice property.
     * 
     */
    public void setDamnodice(int value) {
        this.damnodice = value;
    }

    /**
     * Gets the value of the damsizedice property.
     * 
     */
    public int getDamsizedice() {
        return damsizedice;
    }

    /**
     * Sets the value of the damsizedice property.
     * 
     */
    public void setDamsizedice(int value) {
        this.damsizedice = value;
    }

    /**
     * Gets the value of the damplus property.
     * 
     */
    public int getDamplus() {
        return damplus;
    }

    /**
     * Sets the value of the damplus property.
     * 
     */
    public void setDamplus(int value) {
        this.damplus = value;
    }

}
