//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.25 at 07:22:39 PM CET 
//


package pl.swmud.ns.swmud._1_0.area;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sectiona complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sectiona">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="str" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="int" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="wis" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="dex" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="con" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="cha" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="lck" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sectiona", propOrder = {
    "str",
    "_int",
    "wis",
    "dex",
    "con",
    "cha",
    "lck"
})
public class Sectiona {

    protected short str;
    @XmlElement(name = "int")
    protected short _int;
    protected short wis;
    protected short dex;
    protected short con;
    protected short cha;
    protected short lck;

    /**
     * Gets the value of the str property.
     * 
     */
    public short getStr() {
        return str;
    }

    /**
     * Sets the value of the str property.
     * 
     */
    public void setStr(short value) {
        this.str = value;
    }

    /**
     * Gets the value of the int property.
     * 
     */
    public short getInt() {
        return _int;
    }

    /**
     * Sets the value of the int property.
     * 
     */
    public void setInt(short value) {
        this._int = value;
    }

    /**
     * Gets the value of the wis property.
     * 
     */
    public short getWis() {
        return wis;
    }

    /**
     * Sets the value of the wis property.
     * 
     */
    public void setWis(short value) {
        this.wis = value;
    }

    /**
     * Gets the value of the dex property.
     * 
     */
    public short getDex() {
        return dex;
    }

    /**
     * Sets the value of the dex property.
     * 
     */
    public void setDex(short value) {
        this.dex = value;
    }

    /**
     * Gets the value of the con property.
     * 
     */
    public short getCon() {
        return con;
    }

    /**
     * Sets the value of the con property.
     * 
     */
    public void setCon(short value) {
        this.con = value;
    }

    /**
     * Gets the value of the cha property.
     * 
     */
    public short getCha() {
        return cha;
    }

    /**
     * Sets the value of the cha property.
     * 
     */
    public void setCha(short value) {
        this.cha = value;
    }

    /**
     * Gets the value of the lck property.
     * 
     */
    public short getLck() {
        return lck;
    }

    /**
     * Sets the value of the lck property.
     * 
     */
    public void setLck(short value) {
        this.lck = value;
    }

}
