//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.25 at 07:22:39 PM CET 
//


package pl.swmud.ns.swmud._1_0.area;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sections complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sections">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="saving_poison_death" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="saving_wand" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="saving_para_petri" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="saving_breath" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="saving_spell_staff" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sections", propOrder = {
    "savingPoisonDeath",
    "savingWand",
    "savingParaPetri",
    "savingBreath",
    "savingSpellStaff"
})
public class Sections {

    @XmlElement(name = "saving_poison_death")
    protected int savingPoisonDeath;
    @XmlElement(name = "saving_wand")
    protected int savingWand;
    @XmlElement(name = "saving_para_petri")
    protected int savingParaPetri;
    @XmlElement(name = "saving_breath")
    protected int savingBreath;
    @XmlElement(name = "saving_spell_staff")
    protected int savingSpellStaff;

    /**
     * Gets the value of the savingPoisonDeath property.
     * 
     */
    public int getSavingPoisonDeath() {
        return savingPoisonDeath;
    }

    /**
     * Sets the value of the savingPoisonDeath property.
     * 
     */
    public void setSavingPoisonDeath(int value) {
        this.savingPoisonDeath = value;
    }

    /**
     * Gets the value of the savingWand property.
     * 
     */
    public int getSavingWand() {
        return savingWand;
    }

    /**
     * Sets the value of the savingWand property.
     * 
     */
    public void setSavingWand(int value) {
        this.savingWand = value;
    }

    /**
     * Gets the value of the savingParaPetri property.
     * 
     */
    public int getSavingParaPetri() {
        return savingParaPetri;
    }

    /**
     * Sets the value of the savingParaPetri property.
     * 
     */
    public void setSavingParaPetri(int value) {
        this.savingParaPetri = value;
    }

    /**
     * Gets the value of the savingBreath property.
     * 
     */
    public int getSavingBreath() {
        return savingBreath;
    }

    /**
     * Sets the value of the savingBreath property.
     * 
     */
    public void setSavingBreath(int value) {
        this.savingBreath = value;
    }

    /**
     * Gets the value of the savingSpellStaff property.
     * 
     */
    public int getSavingSpellStaff() {
        return savingSpellStaff;
    }

    /**
     * Sets the value of the savingSpellStaff property.
     * 
     */
    public void setSavingSpellStaff(int value) {
        this.savingSpellStaff = value;
    }

}
